### PR TITLE
Support for running via Jamf

### PR DESCRIPTION
**Pull request by ncsutmf**
Related to #6

### CODE REVIEW

**Comment by ncsutmf** [comment]
Still get an error with this related to this line only when run via Jamf:

```
SCRIPTPATH=$( cd $(dirname $0) ; pwd -P )
```

Not seeing SCRIPTPATH used anywhere else except where it is declared, can it just be removed?

**Comment by ncsutmf** [comment]
So, runs fine when using command line if I add the parameters on my own
```
NukeOffKeychain "/" $(hostname -s) $USER --Jamf --All
```
it works fine even with the dirname line still included, but it still gives usage info when running from Jamf.  Trying to see if I can figure out what Jamf is doing other than just adding the 3 default parameters.

**Comment by ncsutmf** [comment]
Figured it out, Jamf is passing empty string arguments for any arguments not specified by the person configuring the script in a policy, for a total of 11 arguments (default 3 + 8 user supplied).  Ignoring empty string arguments.

The usage error from the `dirname` command does not prevent the script from working, so while `$SCRIPTPATH` does not appear to be used anywhere, leaving it there is not an issue.

Output from Jamf logs:
```
Running script NukeOffKeychain...
Script exit code: 0
Script result: usage: dirname path
Default keychain entries removed
Rights Management keychain entries removed
HelpShift keychain entries removed
```

**Review by pbowden-msft — APPROVED** [review]
Thanks for figuring this out!

**Pull request merged**
